### ISSUE TITLE
Verbessere Fehlermeldungen bei fehlenden Konfigurationsdateien

### ISSUE THREAD

**Issue by luisesiegl** [MaxG87/ButterBackup#7]
Wenn die Konfigurationsdatei fehlt, erscheint ein wenig informativer Stacktrace. Besser wäre eine explizite Warnung, dass die Konfigurationsdatei nicht gefunden wurde.

**Comment by MaxG87** [comment]
Behoben mit ac3c45135a317f2909a6ac387c4e33f8d911642f .
