### ISSUE TITLE
Unterstützung für Automount-Systeme fehlt

### ISSUE THREAD

**Issue by luisesiegl** [MaxG87/ButterBackup#8]
Einige Systeme mounten frisch entschlüsselte Geräte automatisch. In diesen Fällen schlägt der Mount-Befehl fehl und in der Folge scheitert die gesamte Sicherungskopie.

Eine Lösung wäre, zu erkennen, ob das Gerät schon gemountet ist.

**Comment by MaxG87** [comment]
Mit Commit 6a9448ec62cfea21e195e62f27264a937b4e10cc werden automatisch eingehangene Geräte zunächst ausgehangen. Dadurch kann `MountedDevice` das Gerät vollständig übernehmen.

Könntest du prüfen, ob dieser Commit dein Problem löst?
